---
title: "Untitled"
author: "Will Ball"
date: "14/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(scipen = 999)
```


## Libraries

```{r libraries, message = FALSE, warning = FALSE}
library(tidyverse)
library(tidylog)
library(janitor)
library(sf)
library(rmapshaper)
```

## Shapefile with SIMD ranks/deciles

```{r chunk 1, message = FALSE, warning = FALSE}
sf_datazones <- read_sf("Data/Shapefiles/SG_SIMD_2020.shp") %>% 
  clean_names() %>%
  rename(rank = rankv2,
         decile = decilev2,
         inc_rank = inc_rankv2) %>% 
  select(data_zone, dz_name, la_name, ends_with("rank"))%>%
  mutate(across(ends_with("rank"),
         .fns = list(decile = ~ntile(.,10)),
         .names = "{col}_{fn}")) %>% 
  ms_simplify()%>% 
  st_transform(crs = "+proj=longlat +datum=WGS84")

st_write(sf_datazones, "Data/Shapefiles/cleaned.shp", driver = "GPKG") # Default is ESRI driver which abbreviates long column names
```

# Choropleth

```{r}
# Palette
mypalette <- colorFactor(palette = "viridis", domain = sf_datazones$rank_decile, na.color = "transparent")

# Text
mylabels <- paste(
  "Datazone: ", sf_datazones$dz_name,"<br/>",
  "Council Area: ", sf_datazones$la_name,"<br/>",
  "SIMD Decile: ", sf_datazones$rank_decile,
  sep = "") %>% 
  lapply(htmltools::HTML)

# Plot
m <- leaflet(sf_datazones) %>% 
  addTiles() %>% 
  setView( lng = -4.182,
           lat = 56.817,
           zoom = 5.5) %>% 
  addPolygons(
    fillColor = ~mypalette(rank_decile),
    weight = .5,
    opacity = 1,
    color = "grey",
    fillOpacity = .5,
    label = mylabels,
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "12px",
      direction = "auto")) %>% 
  addLegend(
    pal = mypalette,
    values = ~rank_decile,
    opacity = .7,
    title = "SIMD 2020\nDecile",
    position = "bottomright"
  )

m
```

